language: node_js
node_js:
- 8.6.0
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: A+H5WIMhbsI08buNFb8merF96w320AQq/fMBR/uBwkADcvPu+3Ak04xm6zpnW/9Hw3Riu8iSss+FqI0JBdMuWpAWQWB0s7Be8kYiEeA/EFWZ/fUJsem0Z4ITrKhqmkaHSe2hlegGKkK5wOmEdgZMg5w4LWxGKYpa1WZo1kDuGp5VapDj9OTVtNGNbcFek3jbE3CfEggM02ZlRbfjmlpCUnixMcejAN8AD/L1wKf/2EB+8MuGXUYfwUCDXl1VOOslTcVJPcYWZmura7qEjD07iQocVyGeZB7o1erOZkwzdMpirV5d8yIIux8Uoz1g7nqK6hMo2YbMxbKKGzfNuQ8dqwDivuxD3sGeSrvopQA3c6l0NRypxFCB2+egE6ePRjIe2zMS2hn/QgkJybDgYP8AJutOb/NtcUNLzNnr0klpuK7BS5MQE1/PWz426BgI38GHFT/zu7hGY0UwJkpGWlLeIGG1B9X5PDKYiEdRpaY9BQU+YafnqDl6RqznVNlBMiFsoNemIidYP/BQzY0XhmOyZvvikTtbMSLnT40MhifDjceigynk5vvGvtlkJ5Yc1K5o/uRKUxu0eyu/EYCbFo+Qphpz3qd0Q50w5rOpI3IW3p2HM8MUd87MWcIM1TCZoiECXtruhqYQsTuaQNLiJX7LMEWN5ce/mCpl7M9cSUCx4iE=
  app:
    master: hillsrion-devops-production 
    develop: hillsrion-devops-staging
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage